language: node_js
node_js:
- '6'
before_script:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: 'mbutsykin@gmail.com'
  skip_cleanup: true
  api_key:
    secure: X1PjHb/kdtFTlyZf4QrkdOGkqEAA+b5Hk5CMdy04nnta0URf7pZ1DB/l/DA2s03i1HxRRkZ/b1u+k8l68sXTcFAGBqo3rp7hnHDfA3ci+MF7fU2E3z9LZDixE/zgOQn01HTAaYQBoyqQdUcjMOm+NYUOoJPreqO2fweEnbwHYttkGyqd6lH/0lfBl3XhE3H8vLEX1ItNnu7LXYU4FlGMCOxE19eWvGbptvFp4UaOHcvDQ9gKwrK57BJDn8wgmuo+HPIhwYtiOUi2+kHXewXyZ7UMpxAQe3WFcoXvQ998jEMXov9D2V6xtF2jIXUxhWsRY/Ph+McLzDEG9uO2KdaOEEf6Sg56R7zD5QcqiOrCh+52A4yjLxC6YLLXqbmQYPJhszDuXsWPWIUE+0iHdH6FKaxENTkTkI6K38G6lwSBu90jxzgsWPwyHLDOkgH91Td9q6eOYR0ZiO/fCN2sfx1xnUbPEu1+qMKck0e+Vpu7cr2g6uWZiLb/dVkzswNNFlxJUSXRn67BoBrnZFUT2PUm3IuJzz97YLwXQo0QLjSge32qgBSO42Pgz5AfL/ZGe9O1ziOc/NElDVpymOd66RV/hmi00E0HUuXYsxSHXNj63gAopw6GO61OQjYlC8L41qsivZjneu0tbabwo93TP2rnU+Cs0hwHAk864RnRCXFSLv0=
  on:
    tags: true
    branch: master